### ISSUE TITLE
Problème MongoDB quand une clé/valeur  est ajoutée via la route /folder/add-folder-key

### ISSUE THREAD

**Issue by SebastienMantanus** [SebastienMantanus/connectify-back#1]
**Branche**
contacts_v2

**Ficher**
/routes/folders.js

**Route**
/folder/add-folder-key

**Objectif**
Faire en sorte d'éviter les contacts (affiliates) qui n'ont pas de répertoire (en prévision de l'intégration en front). Donc quand cette route est actionnée, elle va rechercher tous les contacts qui n'ont pas de clé "contact_folder, pour leur attribuer le répertoire par défault (_id : 647377874977d0f948b08d71).

**Problème**
La clé est bien ajoutée au contact : quand on requête le contact via son ID on obtient bien : 
![image](https://github.com/SebastienMantanus/connectify-back/assets/113979673/5bbd7c83-2918-417b-9bdc-ae0c6e5bf05b)

Mais dans Compass, on ne voit aucunement cette la clé contact_folder : 
<img width="503" alt="image" src="https://github.com/SebastienMantanus/connectify-back/assets/113979673/b33d15dd-74e6-4661-8467-861edc564233">

J'ai remarqué que la clé venait s'insérer avant le _id du contact, je ne sais pas si c'est la raison du bug, si j'ai fait quelque chose de faux dans le le model Affiliates.js, ou je ne sais quoi encore...

Merci !!!!

**Comment by GwendolineD** [comment]
Salut,

Si je comprend bien, tu veux que ceux qui créent un profil (sans renseigner les infos d'un contact) aient un contact par défaut d'enregistré dans la DB, c'est bien ça ?

Si oui, tu peux le faire au niveau du modèle.  
Exemple : 
```js
ContactName : {type: String, default: "Toto"}
```

Tu as aussi un exemple au deuxième rectangle de code de cette page : https://mongoosejs.com/docs/schematypes.html

**Comment by GwendolineD** [comment]
Essaie de faire un restart comunity => commande à la fin de ce chapitre https://apollo.lereacteur.io/course/60e311961a814c001763e210/63293930c9182e00183c8379
